=== jani-kahkonen/IIO10410/Harjoitukset_5/h05t07/dtd.dtd
<!ELEMENT viikkoX (henkilotiedot, tehtavat)>

<!ELEMENT henkilotiedot (etunimi, sukunimi, opiskelijatunnus?)>
<!ELEMENT etunimi (#PCDATA)>
<!ELEMENT sukunimi (#PCDATA)>
<!ELEMENT opiskelijatunnus (#PCDATA)>

<!ELEMENT tehtavat (tehtava+)>
<!ELEMENT tehtava (#PCDATA)>

=== jani-kahkonen/IIO10410/Harjoitukset_5/h05t07/iio10410-h05.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE viikkoX SYSTEM "dtd.dtd">

<viikkoX>
	<henkilotiedot>
		<etunimi>Jani</etunimi>
		<sukunimi>Kähkönen</sukunimi>
		<opiskelijatunnus>H9575</opiskelijatunnus>
	</henkilotiedot>
	<tehtavat>
		<tehtava>3</tehtava>
		<tehtava>3</tehtava>
		<tehtava>3</tehtava>
		<tehtava>5</tehtava>
		<tehtava>4</tehtava>
		<tehtava>4</tehtava>
		<tehtava>7</tehtava>
	</tehtavat>
</viikkoX>
